name: Send PR Notification Email

on:
  pull_request:
    types: [opened]
    branches:
      - main

jobs:
  send-email:
    runs-on: ubuntu-latest

    steps:
      - name: Send Outlook Email Notification
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.office365.com
          server_port: 587
          username: ${{ secrets.OUTLOOK_USERNAME }}
          password: ${{ secrets.OUTLOOK_PASSWORD }}
          subject: "New PR Created: ${{ github.event.pull_request.title }}"
          to: Prathamesh.Narayan@WinWire.com
          from: Prathamesh.Narayan@WinWire.com
          body: |
            A new PR has been created targeting **main** branch.
            
            PR Title: ${{ github.event.pull_request.title }}
            PR URL: ${{ github.event.pull_request.html_url }}
            Created By: ${{ github.event.pull_request.user.login }}

            Please review and approve.
